/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\tema\gothicTheme.ts
 * Command: astryx theme build src\tema\gothicTheme.ts
 * Generated: 2026-09-01T09:30:03.861Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const gothicIconRegistry: IconRegistry;
export declare const gothicTheme: DefinedTheme;
